Dataset used:   https://drive.google.com/file/d/1d-h-L8e8pnk9435agsN9zvp8xAdQ_YVg/view

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/loan.csv')

In [ ]:
df.head()

,age,annual_income,loan_amount,credit_score,years_employed,existing_loans,savings_amount,married,default
0,59,98040,46243,373,24,2,36244,1,0
1,49,143257,42164,490,17,2,9178,1,0
2,35,81558,47051,355,0,2,1725,1,0
3,63,106205,18318,331,38,2,18477,1,0
4,28,26910,22200,826,2,2,46533,0,0

In [ ]:
df.columns

Index(['age', 'annual_income', 'loan_amount', 'credit_score', 'years_employed',
       'existing_loans', 'savings_amount', 'married', 'default'],
      dtype='object')

In [ ]:
df.shape

(2500, 9)

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             2500 non-null   int64
 1   annual_income   2500 non-null   int64
 2   loan_amount     2500 non-null   int64
 3   credit_score    2500 non-null   int64
 4   years_employed  2500 non-null   int64
 5   existing_loans  2500 non-null   int64
 6   savings_amount  2500 non-null   int64
 7   married         2500 non-null   int64
 8   default         2500 non-null   int64
dtypes: int64(9)
memory usage: 175.9 KB

In [ ]:
df.dtypes

age               int64
annual_income     int64
loan_amount       int64
credit_score      int64
years_employed    int64
existing_loans    int64
savings_amount    int64
married           int64
default           int64
dtype: object

In [ ]:
cols = df.select_dtypes(include=np.number).columns
for col in cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1

  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR

  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print(outliers)

Empty DataFrame
Columns: [age, annual_income, loan_amount, credit_score, years_employed, existing_loans, savings_amount, married, default]
Index: []
Empty DataFrame
Columns: [age, annual_income, loan_amount, credit_score, years_employed, existing_loans, savings_amount, married, default]
Index: []
Empty DataFrame
Columns: [age, annual_income, loan_amount, credit_score, years_employed, existing_loans, savings_amount, married, default]
Index: []
Empty DataFrame
Columns: [age, annual_income, loan_amount, credit_score, years_employed, existing_loans, savings_amount, married, default]
Index: []
Empty DataFrame
Columns: [age, annual_income, loan_amount, credit_score, years_employed, existing_loans, savings_amount, married, default]
Index: []
Empty DataFrame
Columns: [age, annual_income, loan_amount, credit_score, years_employed, existing_loans, savings_amount, married, default]
Index: []
Empty DataFrame
Columns: [age, annual_income, loan_amount, credit_score, years_employed, existing_loans, savings_amount, married, default]
Index: []
Empty DataFrame
Columns: [age, annual_income, loan_amount, credit_score, years_employed, existing_loans, savings_amount, married, default]
Index: []
      age  annual_income  loan_amount  credit_score  years_employed  \
2445   37          80710        29700           568               7

      existing_loans  savings_amount  married  default
2445               4           35319        1        1

In [ ]:
#not removed outliers, as very less. But if we want to remove then following ine to be executed
#df = df[(df[col] >= lower) | (df[col] <= upper)]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

In [ ]:
X = df.iloc[:,:-1]
y = df['default']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=101)

In [ ]:
final_model = DecisionTreeClassifier()
final_model.fit(X_train,y_train)
y_pred = final_model.predict(X_test)

In [ ]:
print("accuracy score is: ", accuracy_score(y_pred,y_test)*100,'%')

accuracy score is:  99.8 %