In [ ]:
#Dataset Link:  https://drive.google.com/file/d/1CGnSSp0DHFUD7Et-140y1fkT4IR-M83t/view?usp=sharing

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/census-income.csv")
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual_income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
df['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [ ]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
annual_income     0
dtype: int64

In [ ]:
df.replace("?",np.nan,inplace=True)

In [ ]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
annual_income        0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(4262)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      30718 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  31978 non-null  object
 14  annual_income   32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(23)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder

LE=LabelEncoder()

for col in df.columns:
  if df[col].dtype=='object':
    df[col]=LE.fit_transform(df[col])

In [ ]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual_income
0,39,5,77516,9,13,4,0,1,4,1,2174,0,40,38,0
1,50,4,83311,9,13,2,3,0,4,1,0,0,13,38,0
2,38,2,215646,11,9,0,5,1,4,1,0,0,40,38,0
3,53,2,234721,1,7,2,5,0,2,1,0,0,40,38,0
4,28,2,338409,9,13,2,9,5,2,0,0,0,40,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,2,257302,7,12,2,12,5,4,0,0,0,38,38,0
32557,40,2,154374,11,9,2,6,0,4,1,0,0,40,38,1
32558,58,2,151910,11,9,6,0,4,4,0,0,0,40,38,0
32559,22,2,201490,11,9,4,0,3,4,1,0,0,20,38,0
32560,52,3,287927,11,9,2,3,5,4,0,15024,0,40,38,1

In [ ]:
x=df.drop('annual_income', axis=1)
y=df['annual_income']

In [ ]:
x

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,39,5,77516,9,13,4,0,1,4,1,2174,0,40,38
1,50,4,83311,9,13,2,3,0,4,1,0,0,13,38
2,38,2,215646,11,9,0,5,1,4,1,0,0,40,38
3,53,2,234721,1,7,2,5,0,2,1,0,0,40,38
4,28,2,338409,9,13,2,9,5,2,0,0,0,40,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,2,257302,7,12,2,12,5,4,0,0,0,38,38
32557,40,2,154374,11,9,2,6,0,4,1,0,0,40,38
32558,58,2,151910,11,9,6,0,4,4,0,0,0,40,38
32559,22,2,201490,11,9,4,0,3,4,1,0,0,20,38
32560,52,3,287927,11,9,2,3,5,4,0,15024,0,40,38

In [ ]:
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: annual_income, Length: 30139, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3, random_state=42)

In [ ]:
x_train

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
12776,39,2,181943,9,13,4,3,1,4,0,0,0,35,38
19947,34,2,269723,11,9,0,3,4,4,0,2977,0,50,38
3208,47,2,297884,0,6,6,6,1,4,1,0,0,40,38
28240,48,2,147860,11,9,2,5,5,2,0,0,0,40,38
8249,44,0,344060,14,15,2,9,0,4,1,0,0,40,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32194,42,5,455553,11,9,4,0,4,2,0,0,0,40,38
5877,37,2,323155,3,2,2,4,0,4,1,0,0,85,25
935,37,2,176900,11,9,2,2,0,4,1,0,0,99,38
17063,49,2,124672,11,9,2,2,0,4,1,0,0,40,38
25543,26,2,358124,11,9,4,7,2,2,0,0,0,40,38

In [ ]:
y_train

12776    0
19947    0
3208     0
28240    0
8249     1
        ..
32194    0
5877     0
935      1
17063    1
25543    0
Name: annual_income, Length: 21097, dtype: int64

In [ ]:
x_test

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
9395,31,2,210008,11,9,4,11,3,4,0,0,0,40,38
3393,33,2,161745,8,11,2,4,0,4,1,0,0,45,38
17020,22,2,378104,11,9,4,5,3,4,1,0,0,40,38
6191,38,2,51838,11,9,2,9,5,4,0,0,0,40,38
465,37,2,126708,11,9,2,0,5,4,0,0,0,60,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15937,34,5,287908,11,9,4,7,3,2,1,0,0,42,38
29346,48,2,498328,0,6,2,13,0,2,1,0,0,40,38
4225,27,3,233724,11,9,5,0,1,4,1,0,0,38,38
28066,46,2,216414,8,11,3,2,4,4,1,0,0,40,38
5245,48,0,94342,9,13,0,3,1,4,1,0,0,45,38

In [ ]:
y_test

9395     0
3393     0
17020    0
6191     0
465      0
        ..
15937    0
29346    0
4225     0
28066    0
5245     0
Name: annual_income, Length: 9042, dtype: int64

#Adaboost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ada_model=AdaBoostClassifier()

ada_model.fit(x_train,y_train)

y_pred=ada_model.predict(x_test)

In [ ]:
from sklearn.metrics import *

acc=accuracy_score(y_test,y_pred)
print(acc)

0.8462729484627295

#Gradient Boost

In [ ]:
#In classification, GB uses LogLoss(Loss function) to  evaluate how well predicted probabilities align with the class labels(0 or 1)
#and penalizes confident, incorrect predictions
#Using LR and the same steps for regression, it reduces the loss function

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model=GradientBoostingClassifier()

gb_model.fit(x_train,y_train)

y_pred=gb_model.predict(x_test)

In [ ]:
from sklearn.metrics import *

acc=accuracy_score(y_test,y_pred)
print(acc)

0.862862198628622

#XGBoost

In [ ]:
#Tianqui Chen
#XGBOOST focuses on: 1. performance,
#2. speed(larger and different datasets)
#3. flexibility(compatible with different languages, OS and libraries)

In [ ]:
#XGBoost uses: 1. Regularization: adding penalties to reduce overfitting by preventing the model from becoming too complex
#2. Parallelization: evaluates possible splits in parallel across features and then picks the best
#3. Tree Pruning: (Pre-pruning: Gradient Boosting), Post-Pruning, saves pre processing time

In [ ]:
#L1(Lasso): adds the sum of the "ABSOLUTE" values of the coefficients(weights) as a penalty to the loss function
#Sets many feature weights to zero because of which automatically feature selection happens

#Add absolute value of weights to the loss function -> forces less important columns to become exactly zero

In [ ]:
#L2(Ridge): adds the sum of the squared values of the coefficients(weights) as a penalty to the loss function
#Shrink all weights uniformly towards zero, but rarely sets them to exact zero.

In [ ]:
#Elastic Net: hybrid of L1 and L2

In [ ]:
#Gradient Boost - General physician, XGBoost - Cardiologist

In [ ]:
from xgboost import XGBClassifier

xgb_model=XGBClassifier()

xgb_model.fit(x_train,y_train)

y_pred=xgb_model.predict(x_test)

In [ ]:
from sklearn.metrics import *

acc=accuracy_score(y_test,y_pred)
print(acc)

0.8651846936518469

In [ ]:
#Dataset Customer Churn- https://drive.google.com/file/d/1nsnQPNTWbxNeXBXczDPIAMqvEyW_NHLR/view?usp=sharing

In [ ]:
# Loss Function: measures how "wrong" a ML model's predictions are.

#Loss in regression: measures the distance between the predicted number and actual number

#Loss in classification: measures how well the predicted probabilities match the actual class labels
# (Log Loss/Cross-Entropy Loss): penalize the model based on how far the predicted probability(eg: 0.8) is from the true label(eg: 1.0)
#If the model is very confident about the wrong answer, the loss becomes extremely high and vice versa